<a href="https://colab.research.google.com/github/ubuntumel/AI_Colab_DeepLearning/blob/main/Cifar10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://colab.research.google.com/drive/1-TA6KDdvBS4xCRqLqb0oXxHtm54t2MGp?usp=sharing

Authors: Meliton Rojas, Bricio Blancas Salgado

In [ ]:
# import cifar10 dataset as well as the models and layers.
import keras
from keras import models
from keras import layers
from keras import optimizers
from keras import activations
from keras.datasets import cifar10

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

This dataset contains 50,000 32 * 32 color training images and 10,000 test images labeled over 10 categories. The inputs are 32 * 32 color images as well as the 3 RGB color channels. The 10 labels are integers 0-9 [airplane, automobile, bird, cat, deer, dog, frog, horse, ship, truck]. The dimensions of this dataset is 60,000 images split 50,000 for training and 10,000 for testing.

In [ ]:
# load training and testing data from cifar10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step

In [ ]:
# Reshape images from (32, 32, 3) to flattened vector of (3072)
# convert to float
x_train = x_train.reshape((x_train.shape[0], 32 * 32 * 3)).astype("float32") / 255.0
x_test  = x_test.reshape((x_test.shape[0],  32 * 32 * 3)).astype("float32") / 255.0

In [ ]:
# build_model function creates a neural network
# Parameters:
# hidden_units: number of neurons per hidden layer
# num_hidden_layers: how many hidden layers
# activation: activation function for hidden layers
# num_classes: number of output classes

def build_model(input_dim = 32 * 32 * 3, hidden_units = 64, num_hidden_layers = 1, activation = "relu", num_classes = 10) -> keras.Model:
  # Create the Sequential model
  model = keras.Sequential(name=f"model_{activation}_{hidden_units}_{num_hidden_layers}h1")

  # Input layer
  model.add(layers.Input(shape=(input_dim,)))

  # add hidden layers dynamically
  for _ in range(num_hidden_layers):
    model.add(layers.Dense(hidden_units, activation=activation))

  # output layer with softmax for multi classification
  model.add(layers.Dense(num_classes, activation="softmax"))

  return model

In [ ]:
# fit_evaluate training and evaluation function
# compiles, trains, and evaluates model
# returns training history, test loss, and test accuracy

def fit_evaluate(model: keras.Model,
                 x_train, y_train,
                 x_test, y_test,
                 optimizer = "rmsprop",
                 loss = "sparse_categorical_crossentropy",
                 epochs = 20,
                 batch_size = 128,
                 validation_split = 0.1,
                 verbose = 2, metrics = None):

  # automatically choose correct accuracy metric if not specified
    if metrics is None:
      if loss == "categorical_crossentropy":
          metrics = ["categorical_accuracy"]
      else:
          metrics = ["sparse_categorical_accuracy"]
    # compile the model
    model.compile(
        optimizer = optimizer,
        loss = loss,
        metrics = ["accuracy"],
    )
    # train the model
    history = model.fit(
        x_train, y_train,
        epochs = epochs,
        batch_size = batch_size,
        validation_split = validation_split,
        verbose = verbose
    )
    # evaluate test data
    test_loss, test_acc = model.evaluate(x_test, y_test, verbose = 0)

    return history, test_loss, test_acc

In [ ]:
# Train 3 models with different activations.
activations_list = ["relu", "tanh", "sigmoid"]
results = []

# train and evaluate each activation function
for activation in activations_list:
  print(f"Training model: {activation}")
  model = build_model(hidden_units = 64, num_hidden_layers = 1, activation = activation)
  history, test_loss, test_acc = fit_evaluate(model, x_train, y_train, x_test, y_test, optimizer="rmsprop", loss = "sparse_categorical_crossentropy", epochs = 20, batch_size = 128, verbose = 2)
  # store results
  results.append({"Activation": activation, "Test Accuracy": float(test_acc)})
#display results sorted by accuracy
df = pd.DataFrame(results).sort_values("Test Accuracy", ascending = False)
display(df)

Training model: relu
Epoch 1/20
352/352 - 4s - 12ms/step - accuracy: 0.2242 - loss: 2.1041 - val_accuracy: 0.3112 - val_loss: 1.9659
Epoch 2/20
352/352 - 4s - 10ms/step - accuracy: 0.3158 - loss: 1.9004 - val_accuracy: 0.3158 - val_loss: 1.8775
Epoch 3/20
352/352 - 3s - 8ms/step - accuracy: 0.3413 - loss: 1.8401 - val_accuracy: 0.3498 - val_loss: 1.8012
Epoch 4/20
352/352 - 4s - 11ms/step - accuracy: 0.3551 - loss: 1.7995 - val_accuracy: 0.3480 - val_loss: 1.8059
Epoch 5/20
352/352 - 3s - 8ms/step - accuracy: 0.3680 - loss: 1.7665 - val_accuracy: 0.3734 - val_loss: 1.7826
Epoch 6/20
352/352 - 3s - 8ms/step - accuracy: 0.3755 - loss: 1.7468 - val_accuracy: 0.3620 - val_loss: 1.7840
Epoch 7/20
352/352 - 3s - 8ms/step - accuracy: 0.3846 - loss: 1.7277 - val_accuracy: 0.3702 - val_loss: 1.7582
Epoch 8/20
352/352 - 4s - 11ms/step - accuracy: 0.3902 - loss: 1.7124 - val_accuracy: 0.3106 - val_loss: 2.0007
Epoch 9/20
352/352 - 3s - 8ms/step - accuracy: 0.3936 - loss: 1.6972 - val_accuracy: 0.3536 - val_loss: 1.7840
Epoch 10/20
352/352 - 3s - 8ms/step - accuracy: 0.4004 - loss: 1.6876 - val_accuracy: 0.3996 - val_loss: 1.6788
Epoch 11/20
352/352 - 3s - 8ms/step - accuracy: 0.4064 - loss: 1.6744 - val_accuracy: 0.3800 - val_loss: 1.7542
Epoch 12/20
352/352 - 6s - 17ms/step - accuracy: 0.4092 - loss: 1.6639 - val_accuracy: 0.4036 - val_loss: 1.6692
Epoch 13/20
352/352 - 3s - 8ms/step - accuracy: 0.4135 - loss: 1.6550 - val_accuracy: 0.3930 - val_loss: 1.6982
Epoch 14/20
352/352 - 3s - 8ms/step - accuracy: 0.4150 - loss: 1.6492 - val_accuracy: 0.4106 - val_loss: 1.6707
Epoch 15/20
352/352 - 3s - 8ms/step - accuracy: 0.4189 - loss: 1.6370 - val_accuracy: 0.3862 - val_loss: 1.7217
Epoch 16/20
352/352 - 4s - 11ms/step - accuracy: 0.4190 - loss: 1.6341 - val_accuracy: 0.3612 - val_loss: 1.7744
Epoch 17/20
352/352 - 4s - 12ms/step - accuracy: 0.4238 - loss: 1.6213 - val_accuracy: 0.3890 - val_loss: 1.7116
Epoch 18/20
352/352 - 5s - 15ms/step - accuracy: 0.4262 - loss: 1.6153 - val_accuracy: 0.3588 - val_loss: 1.7609
Epoch 19/20
352/352 - 6s - 18ms/step - accuracy: 0.4288 - loss: 1.6080 - val_accuracy: 0.3982 - val_loss: 1.6928
Epoch 20/20
352/352 - 3s - 8ms/step - accuracy: 0.4297 - loss: 1.6020 - val_accuracy: 0.4136 - val_loss: 1.6539
Training model: tanh
Epoch 1/20
352/352 - 5s - 13ms/step - accuracy: 0.2491 - loss: 2.0855 - val_accuracy: 0.3024 - val_loss: 1.9617
Epoch 2/20
352/352 - 3s - 7ms/step - accuracy: 0.3288 - loss: 1.8680 - val_accuracy: 0.3058 - val_loss: 1.9579
Epoch 3/20
352/352 - 3s - 8ms/step - accuracy: 0.3611 - loss: 1.7921 - val_accuracy: 0.3726 - val_loss: 1.7413
Epoch 4/20
352/352 - 3s - 8ms/step - accuracy: 0.3783 - loss: 1.7372 - val_accuracy: 0.3626 - val_loss: 1.8064
Epoch 5/20
352/352 - 4s - 10ms/step - accuracy: 0.3918 - loss: 1.7089 - val_accuracy: 0.3990 - val_loss: 1.7159
Epoch 6/20
352/352 - 3s - 8ms/step - accuracy: 0.4040 - loss: 1.6777 - val_accuracy: 0.3916 - val_loss: 1.7081
Epoch 7/20
352/352 - 5s - 14ms/step - accuracy: 0.4113 - loss: 1.6553 - val_accuracy: 0.3962 - val_loss: 1.6872
Epoch 8/20
352/352 - 3s - 8ms/step - accuracy: 0.4214 - loss: 1.6284 - val_accuracy: 0.3874 - val_loss: 1.7287
Epoch 9/20
352/352 - 4s - 11ms/step - accuracy: 0.4270 - loss: 1.6114 - val_accuracy: 0.4078 - val_loss: 1.6618
Epoch 10/20
352/352 - 3s - 8ms/step - accuracy: 0.4335 - loss: 1.5950 - val_accuracy: 0.4076 - val_loss: 1.6617
Epoch 11/20
352/352 - 3s - 8ms/step - accuracy: 0.4373 - loss: 1.5840 - val_accuracy: 0.4038 - val_loss: 1.6742
Epoch 12/20
352/352 - 3s - 8ms/step - accuracy: 0.4425 - loss: 1.5673 - val_accuracy: 0.4142 - val_loss: 1.6512
Epoch 13/20
352/352 - 4s - 11ms/step - accuracy: 0.4444 - loss: 1.5592 - val_accuracy: 0.3980 - val_loss: 1.6919
Epoch 14/20
352/352 - 3s - 8ms/step - accuracy: 0.4490 - loss: 1.5446 - val_accuracy: 0.4268 - val_loss: 1.6112
Epoch 15/20
352/352 - 3s - 8ms/step - accuracy: 0.4547 - loss: 1.5344 - val_accuracy: 0.4326 - val_loss: 1.6399
Epoch 16/20
352/352 - 3s - 8ms/step - accuracy: 0.4578 - loss: 1.5242 - val_accuracy: 0.4010 - val_loss: 1.6960
Epoch 17/20
352/352 - 3s - 9ms/step - accuracy: 0.4625 - loss: 1.5122 - val_accuracy: 0.4276 - val_loss: 1.6452
Epoch 18/20
352/352 - 5s - 13ms/step - accuracy: 0.4624 - loss: 1.5088 - val_accuracy: 0.4220 - val_loss: 1.6444
Epoch 19/20
352/352 - 3s - 8ms/step - accuracy: 0.4682 - loss: 1.4952 - val_accuracy: 0.4352 - val_loss: 1.5934
Epoch 20/20
352/352 - 3s - 8ms/step - accuracy: 0.4733 - loss: 1.4874 - val_accuracy: 0.4162 - val_loss: 1.6533
Training model: sigmoid
Epoch 1/20
352/352 - 4s - 12ms/step - accuracy: 0.2932 - loss: 1.9654 - val_accuracy: 0.3252 - val_loss: 1.8448
Epoch 2/20
352/352 - 3s - 7ms/step - accuracy: 0.3608 - loss: 1.7978 - val_accuracy: 0.3446 - val_loss: 1.8104
Epoch 3/20
352/352 - 3s - 8ms/step - accuracy: 0.3886 - loss: 1.7342 - val_accuracy: 0.3688 - val_loss: 1.7649
Epoch 4/20
352/352 - 6s - 16ms/step - accuracy: 0.4046 - loss: 1.6845 - val_accuracy: 0.3958 - val_loss: 1.7096
Epoch 5/20
352/352 - 3s - 8ms/step - accuracy: 0.4182 - loss: 1.6493 - val_accuracy: 0.4088 - val_loss: 1.6658
Epoch 6/20
352/352 - 3s - 8ms/step - accuracy: 0.4268 - loss: 1.6227 - val_accuracy: 0.4046 - val_loss: 1.6838
Epoch 7/20
352/352 - 3s - 7ms/step - accuracy: 0.4374 - loss: 1.5950 - val_accuracy: 0.4228 - val_loss: 1.6265
Epoch 8/20
352/352 - 3s - 8ms/step - accuracy: 0.4454 - loss: 1.5739 - val_accuracy: 0.4406 - val_loss: 1.5910
Epoch 9/20
352/352 - 3s - 10ms/step - accuracy: 0.4500 - loss: 1.5542 - val_accuracy: 0.3934 - val_loss: 1.6741
Epoch 10/20
352/352 - 3s - 8ms/step - accuracy: 0.4536 - loss: 1.5408 - val_accuracy: 0.4256 - val_loss: 1.6233
Epoch 11/20
352/352 - 3s - 7ms/step - accuracy: 0.4638 - loss: 1.5240 - val_accuracy: 0.4216 - val_loss: 1.6634
Epoch 12/20
352/352 - 3s - 7ms/step - accuracy: 0.4670 - loss: 1.5118 - val_accuracy: 0.4498 - val_loss: 1.5679
Epoch 13/20
352/352 - 4s - 11ms/step - accuracy: 0.4706 - loss: 1.4980 - val_accuracy: 0.4484 - val_loss: 1.5650
Epoch 14/20
352/352 - 4s - 11ms/step - accuracy: 0.4746 - loss: 1.4826 - val_accuracy: 0.4448 - val_loss: 1.5546
Epoch 15/20
352/352 - 3s - 8ms/step - accuracy: 0.4796 - loss: 1.4732 - val_accuracy: 0.4602 - val_loss: 1.5200
Epoch 16/20
352/352 - 3s - 8ms/step - accuracy: 0.4858 - loss: 1.4616 - val_accuracy: 0.4448 - val_loss: 1.5793
Epoch 17/20
352/352 - 4s - 11ms/step - accuracy: 0.4877 - loss: 1.4491 - val_accuracy: 0.4344 - val_loss: 1.6222
Epoch 18/20
352/352 - 3s - 8ms/step - accuracy: 0.4901 - loss: 1.4419 - val_accuracy: 0.4488 - val_loss: 1.5604
Epoch 19/20
352/352 - 3s - 7ms/step - accuracy: 0.4971 - loss: 1.4330 - val_accuracy: 0.4198 - val_loss: 1.6852
Epoch 20/20
352/352 - 3s - 8ms/step - accuracy: 0.4988 - loss: 1.4239 - val_accuracy: 0.4602 - val_loss: 1.5450

  Activation  Test Accuracy
2    sigmoid         0.4533
1       tanh         0.4148
0       relu         0.4134

In [ ]:
# Identify best activation function based on test accuracy
best_activation = df.iloc[0]["Activation"]
best_accuracy = df.iloc[0]["Test Accuracy"]
print(f"\nBest activation: {best_activation} (test accuracy = {best_accuracy:.4f})")

Best activation: sigmoid (test accuracy = 0.4533)

In [ ]:
# Model tuning testing different hidden layer sizes 128, 256, 512
tuning_results = []

for units in [128, 256, 512]:
  print(f"Tuning: units = {units}, layers = 1, activation = {best_activation}")
  model = build_model(hidden_units = units, num_hidden_layers = 1, activation = best_activation)

  history, test_loss, test_acc = fit_evaluate(model, x_train, y_train, x_test, y_test, optimizer="rmsprop", loss = "sparse_categorical_crossentropy", epochs = 20, batch_size = 128, verbose = 2)
  tuning_results.append({"Stage": "Units Sweeps (1 layer)", "Activation": best_activation, "Hidden Units": units, "# Hidden Layers": 1, "Optimizer": "rmsprop", "Loss": "sparse_categorical_crossentropy", "Test Accuracy": float(test_acc)})

Tuning: units = 128, layers = 1, activation = sigmoid
Epoch 1/20
352/352 - 8s - 22ms/step - accuracy: 0.2933 - loss: 1.9631 - val_accuracy: 0.3040 - val_loss: 1.8889
Epoch 2/20
352/352 - 4s - 10ms/step - accuracy: 0.3631 - loss: 1.7889 - val_accuracy: 0.3602 - val_loss: 1.8033
Epoch 3/20
352/352 - 5s - 14ms/step - accuracy: 0.3928 - loss: 1.7140 - val_accuracy: 0.3796 - val_loss: 1.7293
Epoch 4/20
352/352 - 4s - 10ms/step - accuracy: 0.4108 - loss: 1.6604 - val_accuracy: 0.3962 - val_loss: 1.7129
Epoch 5/20
352/352 - 5s - 15ms/step - accuracy: 0.4260 - loss: 1.6207 - val_accuracy: 0.3998 - val_loss: 1.6755
Epoch 6/20
352/352 - 5s - 14ms/step - accuracy: 0.4386 - loss: 1.5866 - val_accuracy: 0.4214 - val_loss: 1.6340
Epoch 7/20
352/352 - 4s - 10ms/step - accuracy: 0.4453 - loss: 1.5609 - val_accuracy: 0.4434 - val_loss: 1.5764
Epoch 8/20
352/352 - 5s - 15ms/step - accuracy: 0.4566 - loss: 1.5345 - val_accuracy: 0.4508 - val_loss: 1.5555
Epoch 9/20
352/352 - 5s - 13ms/step - accuracy: 0.4680 - loss: 1.5091 - val_accuracy: 0.4364 - val_loss: 1.5862
Epoch 10/20
352/352 - 4s - 11ms/step - accuracy: 0.4732 - loss: 1.4889 - val_accuracy: 0.4084 - val_loss: 1.6438
Epoch 11/20
352/352 - 4s - 10ms/step - accuracy: 0.4803 - loss: 1.4688 - val_accuracy: 0.4454 - val_loss: 1.5603
Epoch 12/20
352/352 - 5s - 14ms/step - accuracy: 0.4876 - loss: 1.4506 - val_accuracy: 0.4596 - val_loss: 1.5357
Epoch 13/20
352/352 - 4s - 10ms/step - accuracy: 0.4923 - loss: 1.4343 - val_accuracy: 0.4724 - val_loss: 1.4950
Epoch 14/20
352/352 - 4s - 10ms/step - accuracy: 0.4990 - loss: 1.4189 - val_accuracy: 0.4556 - val_loss: 1.5329
Epoch 15/20
352/352 - 6s - 18ms/step - accuracy: 0.5024 - loss: 1.4059 - val_accuracy: 0.4750 - val_loss: 1.4777
Epoch 16/20
352/352 - 4s - 12ms/step - accuracy: 0.5076 - loss: 1.3897 - val_accuracy: 0.4432 - val_loss: 1.5745
Epoch 17/20
352/352 - 8s - 22ms/step - accuracy: 0.5126 - loss: 1.3784 - val_accuracy: 0.4782 - val_loss: 1.4786
Epoch 18/20
352/352 - 7s - 21ms/step - accuracy: 0.5170 - loss: 1.3669 - val_accuracy: 0.4706 - val_loss: 1.4745
Epoch 19/20
352/352 - 6s - 18ms/step - accuracy: 0.5209 - loss: 1.3572 - val_accuracy: 0.4768 - val_loss: 1.4748
Epoch 20/20
352/352 - 5s - 14ms/step - accuracy: 0.5250 - loss: 1.3461 - val_accuracy: 0.4670 - val_loss: 1.5014
Tuning: units = 256, layers = 1, activation = sigmoid
Epoch 1/20
352/352 - 8s - 22ms/step - accuracy: 0.2906 - loss: 1.9754 - val_accuracy: 0.3082 - val_loss: 1.8776
Epoch 2/20
352/352 - 6s - 17ms/step - accuracy: 0.3647 - loss: 1.7789 - val_accuracy: 0.3564 - val_loss: 1.7995
Epoch 3/20
352/352 - 9s - 25ms/step - accuracy: 0.3967 - loss: 1.6975 - val_accuracy: 0.3972 - val_loss: 1.6721
Epoch 4/20
352/352 - 8s - 23ms/step - accuracy: 0.4161 - loss: 1.6443 - val_accuracy: 0.3884 - val_loss: 1.7273
Epoch 5/20
352/352 - 9s - 25ms/step - accuracy: 0.4321 - loss: 1.6009 - val_accuracy: 0.4024 - val_loss: 1.6820
Epoch 6/20
352/352 - 10s - 30ms/step - accuracy: 0.4424 - loss: 1.5637 - val_accuracy: 0.4026 - val_loss: 1.6620
Epoch 7/20
352/352 - 8s - 24ms/step - accuracy: 0.4563 - loss: 1.5338 - val_accuracy: 0.4188 - val_loss: 1.6782
Epoch 8/20
352/352 - 10s - 29ms/step - accuracy: 0.4664 - loss: 1.5044 - val_accuracy: 0.4446 - val_loss: 1.5807
Epoch 9/20
352/352 - 7s - 19ms/step - accuracy: 0.4767 - loss: 1.4841 - val_accuracy: 0.4522 - val_loss: 1.5593
Epoch 10/20
352/352 - 11s - 32ms/step - accuracy: 0.4840 - loss: 1.4571 - val_accuracy: 0.4504 - val_loss: 1.5639
Epoch 11/20
352/352 - 8s - 23ms/step - accuracy: 0.4895 - loss: 1.4385 - val_accuracy: 0.4576 - val_loss: 1.5630
Epoch 12/20
352/352 - 8s - 24ms/step - accuracy: 0.4976 - loss: 1.4168 - val_accuracy: 0.4832 - val_loss: 1.4615
Epoch 13/20
352/352 - 7s - 21ms/step - accuracy: 0.5058 - loss: 1.4002 - val_accuracy: 0.4424 - val_loss: 1.5631
Epoch 14/20
352/352 - 6s - 18ms/step - accuracy: 0.5148 - loss: 1.3796 - val_accuracy: 0.4618 - val_loss: 1.5266
Epoch 15/20
352/352 - 11s - 30ms/step - accuracy: 0.5155 - loss: 1.3659 - val_accuracy: 0.4412 - val_loss: 1.5846
Epoch 16/20
352/352 - 8s - 23ms/step - accuracy: 0.5250 - loss: 1.3474 - val_accuracy: 0.4800 - val_loss: 1.4693
Epoch 17/20
352/352 - 7s - 20ms/step - accuracy: 0.5264 - loss: 1.3312 - val_accuracy: 0.4874 - val_loss: 1.4779
Epoch 18/20
352/352 - 7s - 19ms/step - accuracy: 0.5338 - loss: 1.3197 - val_accuracy: 0.4692 - val_loss: 1.4937
Epoch 19/20
352/352 - 7s - 20ms/step - accuracy: 0.5370 - loss: 1.3049 - val_accuracy: 0.4836 - val_loss: 1.4769
Epoch 20/20
352/352 - 8s - 23ms/step - accuracy: 0.5440 - loss: 1.2903 - val_accuracy: 0.4830 - val_loss: 1.4721
Tuning: units = 512, layers = 1, activation = sigmoid
Epoch 1/20
352/352 - 13s - 36ms/step - accuracy: 0.2845 - loss: 2.0097 - val_accuracy: 0.3288 - val_loss: 1.8673
Epoch 2/20
352/352 - 13s - 38ms/step - accuracy: 0.3594 - loss: 1.7882 - val_accuracy: 0.3510 - val_loss: 1.8208
Epoch 3/20
352/352 - 12s - 35ms/step - accuracy: 0.3932 - loss: 1.6972 - val_accuracy: 0.3412 - val_loss: 1.8530
Epoch 4/20
352/352 - 20s - 56ms/step - accuracy: 0.4161 - loss: 1.6424 - val_accuracy: 0.4018 - val_loss: 1.6612
Epoch 5/20
352/352 - 21s - 60ms/step - accuracy: 0.4333 - loss: 1.5964 - val_accuracy: 0.4190 - val_loss: 1.6489
Epoch 6/20
352/352 - 18s - 52ms/step - accuracy: 0.4463 - loss: 1.5533 - val_accuracy: 0.4210 - val_loss: 1.6415
Epoch 7/20
352/352 - 11s - 33ms/step - accuracy: 0.4589 - loss: 1.5194 - val_accuracy: 0.3580 - val_loss: 1.7500
Epoch 8/20
352/352 - 11s - 31ms/step - accuracy: 0.4680 - loss: 1.4920 - val_accuracy: 0.4584 - val_loss: 1.5267
Epoch 9/20
352/352 - 11s - 32ms/step - accuracy: 0.4803 - loss: 1.4630 - val_accuracy: 0.4106 - val_loss: 1.6815
Epoch 10/20
352/352 - 22s - 62ms/step - accuracy: 0.4902 - loss: 1.4361 - val_accuracy: 0.4758 - val_loss: 1.4701
Epoch 11/20
352/352 - 11s - 30ms/step - accuracy: 0.5013 - loss: 1.4163 - val_accuracy: 0.4792 - val_loss: 1.4642
Epoch 12/20
352/352 - 22s - 64ms/step - accuracy: 0.5061 - loss: 1.3896 - val_accuracy: 0.4640 - val_loss: 1.5359
Epoch 13/20
352/352 - 11s - 32ms/step - accuracy: 0.5102 - loss: 1.3743 - val_accuracy: 0.4700 - val_loss: 1.5041
Epoch 14/20
352/352 - 11s - 32ms/step - accuracy: 0.5199 - loss: 1.3539 - val_accuracy: 0.4456 - val_loss: 1.5824
Epoch 15/20
352/352 - 11s - 32ms/step - accuracy: 0.5267 - loss: 1.3340 - val_accuracy: 0.4660 - val_loss: 1.5042
Epoch 16/20
352/352 - 11s - 31ms/step - accuracy: 0.5337 - loss: 1.3152 - val_accuracy: 0.4484 - val_loss: 1.5429
Epoch 17/20
352/352 - 11s - 33ms/step - accuracy: 0.5398 - loss: 1.2981 - val_accuracy: 0.4306 - val_loss: 1.5912
Epoch 18/20
352/352 - 11s - 30ms/step - accuracy: 0.5484 - loss: 1.2779 - val_accuracy: 0.4946 - val_loss: 1.4500
Epoch 19/20
352/352 - 11s - 31ms/step - accuracy: 0.5496 - loss: 1.2649 - val_accuracy: 0.4906 - val_loss: 1.4626
Epoch 20/20
352/352 - 21s - 59ms/step - accuracy: 0.5598 - loss: 1.2461 - val_accuracy: 0.4834 - val_loss: 1.4551

In [ ]:
# determine the units
df_units = pd.DataFrame([r for r in tuning_results if r["Stage"] == "Units Sweeps (1 layer)"])
best_units = int(df_units.sort_values("Test Accuracy", ascending=False).iloc[0]["Hidden Units"])
print(f"\nBest hidden units: {best_units}")

Best hidden units: 512

In [ ]:
# add hidden layer
print(f"Tuning: units = {best_units}, layers = 2, activation = {best_activation}")
model_extra = build_model(hidden_units=best_units, num_hidden_layers=2, activation=best_activation)

hist_extra, loss_extra, acc_extra = fit_evaluate(
    model_extra,
    x_train, y_train,
    x_test, y_test,
    optimizer="rmsprop",
    loss="sparse_categorical_crossentropy",
    epochs=20,
    batch_size=128,
    verbose=2
)

tuning_results.append({
    "Stage": "Add hidden layer",
    "Activation": best_activation,
    "Hidden Units": best_units,
    "# Hidden Layers": 2,
    "Optimizer": "rmsprop",
    "Loss": "sparse_categorical_crossentropy",
    "Test Accuracy": float(acc_extra)
})

# changing optimizer
print(f"Tuning: Adam optimizer (units={best_units}, layers=2, act={best_activation})")
model_adam = build_model(hidden_units=best_units, num_hidden_layers=2, activation=best_activation)

hist_adam, loss_adam, acc_adam = fit_evaluate(
    model_adam,
    x_train, y_train,
    x_test, y_test,
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    epochs=20,
    batch_size=128,
    verbose=2
)

tuning_results.append({
    "Stage": "Change optimizer",
    "Activation": best_activation,
    "Hidden Units": best_units,
    "# Hidden Layers": 2,
    "Optimizer": "adam",
    "Loss": "sparse_categorical_crossentropy",
    "Test Accuracy": float(acc_adam)
})

Tuning: units = 512, layers = 2, activation = sigmoid
Epoch 1/20
352/352 - 14s - 40ms/step - accuracy: 0.2615 - loss: 2.0194 - val_accuracy: 0.2426 - val_loss: 2.1693
Epoch 2/20
352/352 - 13s - 38ms/step - accuracy: 0.3479 - loss: 1.8071 - val_accuracy: 0.3746 - val_loss: 1.7583
Epoch 3/20
352/352 - 20s - 58ms/step - accuracy: 0.3879 - loss: 1.7107 - val_accuracy: 0.4004 - val_loss: 1.6776
Epoch 4/20
352/352 - 13s - 38ms/step - accuracy: 0.4136 - loss: 1.6454 - val_accuracy: 0.3972 - val_loss: 1.6568
Epoch 5/20
352/352 - 13s - 38ms/step - accuracy: 0.4296 - loss: 1.5965 - val_accuracy: 0.4388 - val_loss: 1.5797
Epoch 6/20
352/352 - 13s - 38ms/step - accuracy: 0.4433 - loss: 1.5544 - val_accuracy: 0.3952 - val_loss: 1.6590
Epoch 7/20
352/352 - 15s - 42ms/step - accuracy: 0.4548 - loss: 1.5231 - val_accuracy: 0.4296 - val_loss: 1.5688
Epoch 8/20
352/352 - 13s - 36ms/step - accuracy: 0.4674 - loss: 1.4949 - val_accuracy: 0.4700 - val_loss: 1.4798
Epoch 9/20
352/352 - 13s - 37ms/step - accuracy: 0.4760 - loss: 1.4648 - val_accuracy: 0.4204 - val_loss: 1.6445
Epoch 10/20
352/352 - 21s - 59ms/step - accuracy: 0.4871 - loss: 1.4394 - val_accuracy: 0.4484 - val_loss: 1.6094
Epoch 11/20
352/352 - 13s - 38ms/step - accuracy: 0.4945 - loss: 1.4163 - val_accuracy: 0.4666 - val_loss: 1.4944
Epoch 12/20
352/352 - 21s - 59ms/step - accuracy: 0.5017 - loss: 1.3941 - val_accuracy: 0.4574 - val_loss: 1.4943
Epoch 13/20
352/352 - 20s - 58ms/step - accuracy: 0.5126 - loss: 1.3697 - val_accuracy: 0.4902 - val_loss: 1.4468
Epoch 14/20
352/352 - 15s - 42ms/step - accuracy: 0.5186 - loss: 1.3499 - val_accuracy: 0.4930 - val_loss: 1.4198
Epoch 15/20
352/352 - 14s - 39ms/step - accuracy: 0.5225 - loss: 1.3320 - val_accuracy: 0.4886 - val_loss: 1.4320
Epoch 16/20
352/352 - 20s - 57ms/step - accuracy: 0.5280 - loss: 1.3193 - val_accuracy: 0.4704 - val_loss: 1.4753
Epoch 17/20
352/352 - 13s - 38ms/step - accuracy: 0.5362 - loss: 1.3012 - val_accuracy: 0.4712 - val_loss: 1.4876
Epoch 18/20
352/352 - 22s - 62ms/step - accuracy: 0.5416 - loss: 1.2831 - val_accuracy: 0.4874 - val_loss: 1.4473
Epoch 19/20
352/352 - 17s - 47ms/step - accuracy: 0.5499 - loss: 1.2674 - val_accuracy: 0.4934 - val_loss: 1.4247
Epoch 20/20
352/352 - 18s - 51ms/step - accuracy: 0.5544 - loss: 1.2533 - val_accuracy: 0.4808 - val_loss: 1.5044
Tuning: Adam optimizer (units=512, layers=2, act=sigmoid)
Epoch 1/20
352/352 - 19s - 55ms/step - accuracy: 0.3143 - loss: 1.8958 - val_accuracy: 0.3514 - val_loss: 1.7918
Epoch 2/20
352/352 - 19s - 53ms/step - accuracy: 0.3924 - loss: 1.6876 - val_accuracy: 0.4116 - val_loss: 1.6523
Epoch 3/20
352/352 - 21s - 59ms/step - accuracy: 0.4192 - loss: 1.6161 - val_accuracy: 0.4316 - val_loss: 1.6092
Epoch 4/20
352/352 - 19s - 53ms/step - accuracy: 0.4398 - loss: 1.5674 - val_accuracy: 0.4342 - val_loss: 1.5861
Epoch 5/20
352/352 - 16s - 45ms/step - accuracy: 0.4572 - loss: 1.5205 - val_accuracy: 0.4376 - val_loss: 1.5622
Epoch 6/20
352/352 - 24s - 68ms/step - accuracy: 0.4648 - loss: 1.4951 - val_accuracy: 0.4586 - val_loss: 1.5206
Epoch 7/20
352/352 - 18s - 52ms/step - accuracy: 0.4771 - loss: 1.4601 - val_accuracy: 0.4662 - val_loss: 1.4942
Epoch 8/20
352/352 - 15s - 44ms/step - accuracy: 0.4872 - loss: 1.4386 - val_accuracy: 0.4604 - val_loss: 1.4922
Epoch 9/20
352/352 - 16s - 44ms/step - accuracy: 0.4930 - loss: 1.4174 - val_accuracy: 0.4582 - val_loss: 1.5002
Epoch 10/20
352/352 - 16s - 47ms/step - accuracy: 0.4998 - loss: 1.4010 - val_accuracy: 0.4726 - val_loss: 1.4668
Epoch 11/20
352/352 - 16s - 46ms/step - accuracy: 0.5040 - loss: 1.3780 - val_accuracy: 0.4702 - val_loss: 1.4726
Epoch 12/20
352/352 - 16s - 46ms/step - accuracy: 0.5104 - loss: 1.3599 - val_accuracy: 0.4762 - val_loss: 1.4549
Epoch 13/20
352/352 - 19s - 53ms/step - accuracy: 0.5198 - loss: 1.3383 - val_accuracy: 0.4828 - val_loss: 1.4538
Epoch 14/20
352/352 - 18s - 51ms/step - accuracy: 0.5237 - loss: 1.3246 - val_accuracy: 0.4936 - val_loss: 1.4449
Epoch 15/20
352/352 - 18s - 52ms/step - accuracy: 0.5316 - loss: 1.3085 - val_accuracy: 0.4814 - val_loss: 1.4449
Epoch 16/20
352/352 - 19s - 54ms/step - accuracy: 0.5379 - loss: 1.2919 - val_accuracy: 0.4996 - val_loss: 1.4112
Epoch 17/20
352/352 - 16s - 46ms/step - accuracy: 0.5425 - loss: 1.2800 - val_accuracy: 0.5060 - val_loss: 1.3969
Epoch 18/20
352/352 - 23s - 66ms/step - accuracy: 0.5478 - loss: 1.2633 - val_accuracy: 0.5056 - val_loss: 1.3956
Epoch 19/20
352/352 - 18s - 50ms/step - accuracy: 0.5506 - loss: 1.2480 - val_accuracy: 0.5000 - val_loss: 1.4357
Epoch 20/20
352/352 - 20s - 56ms/step - accuracy: 0.5566 - loss: 1.2345 - val_accuracy: 0.5090 - val_loss: 1.4017

In [ ]:
# Switch labels to one-hot and use categorical_crossentropy
# Change loss function
from keras.utils import to_categorical
y_train_oh = to_categorical(y_train, 10)
y_test_oh  = to_categorical(y_test, 10)


print(f"Tuning: categorical_crossentropy (one-hot) + Adam (units = {best_units}, layers = 2, activation = {best_activation})")
model_cce = build_model(hidden_units=best_units, num_hidden_layers=2, activation=best_activation)

hist_cce, loss_cce, acc_cce = fit_evaluate(
    model_cce,
    x_train, y_train_oh,
    x_test, y_test_oh,
    optimizer="adam",
    loss="categorical_crossentropy",
    epochs=20,
    batch_size=128,
    verbose=2
)

tuning_results.append({
    "Stage": "Change loss (one-hot)",
    "Activation": best_activation,
    "Hidden Units": best_units,
    "# Hidden Layers": 2,
    "Optimizer": "adam",
    "Loss": "categorical_crossentropy",
    "Test Accuracy": float(acc_cce)
})

# display tuning results and what seems to be the best
df_tune = pd.DataFrame(tuning_results).sort_values("Test Accuracy", ascending=False)
print("\nResults:")
display(df_tune)


best_step5 = df_tune.iloc[0]
print("\nBest tuned configuration:")
display(df_tune.head(1))

Tuning: categorical_crossentropy (one-hot) + Adam (units = 512, layers = 2, activation = sigmoid)
Epoch 1/20
352/352 - 20s - 57ms/step - accuracy: 0.3072 - loss: 1.9131 - val_accuracy: 0.3640 - val_loss: 1.7975
Epoch 2/20
352/352 - 18s - 50ms/step - accuracy: 0.3913 - loss: 1.6993 - val_accuracy: 0.4162 - val_loss: 1.6592
Epoch 3/20
352/352 - 17s - 48ms/step - accuracy: 0.4199 - loss: 1.6233 - val_accuracy: 0.4216 - val_loss: 1.6377
Epoch 4/20
352/352 - 19s - 54ms/step - accuracy: 0.4393 - loss: 1.5651 - val_accuracy: 0.4458 - val_loss: 1.5700
Epoch 5/20
352/352 - 17s - 48ms/step - accuracy: 0.4536 - loss: 1.5343 - val_accuracy: 0.4218 - val_loss: 1.6181
Epoch 6/20
352/352 - 22s - 63ms/step - accuracy: 0.4620 - loss: 1.5050 - val_accuracy: 0.4568 - val_loss: 1.5197
Epoch 7/20
352/352 - 16s - 45ms/step - accuracy: 0.4752 - loss: 1.4683 - val_accuracy: 0.4614 - val_loss: 1.5093
Epoch 8/20
352/352 - 17s - 49ms/step - accuracy: 0.4830 - loss: 1.4504 - val_accuracy: 0.4656 - val_loss: 1.4841
Epoch 9/20
352/352 - 18s - 50ms/step - accuracy: 0.4897 - loss: 1.4216 - val_accuracy: 0.4772 - val_loss: 1.4814
Epoch 10/20
352/352 - 18s - 50ms/step - accuracy: 0.5027 - loss: 1.3942 - val_accuracy: 0.4734 - val_loss: 1.4738
Epoch 11/20
352/352 - 20s - 56ms/step - accuracy: 0.5096 - loss: 1.3709 - val_accuracy: 0.4662 - val_loss: 1.5090
Epoch 12/20
352/352 - 18s - 52ms/step - accuracy: 0.5115 - loss: 1.3674 - val_accuracy: 0.4712 - val_loss: 1.4858
Epoch 13/20
352/352 - 15s - 41ms/step - accuracy: 0.5191 - loss: 1.3465 - val_accuracy: 0.4780 - val_loss: 1.4885
Epoch 14/20
352/352 - 14s - 41ms/step - accuracy: 0.5274 - loss: 1.3195 - val_accuracy: 0.4752 - val_loss: 1.4898
Epoch 15/20
352/352 - 15s - 43ms/step - accuracy: 0.5307 - loss: 1.3136 - val_accuracy: 0.5024 - val_loss: 1.4140
Epoch 16/20
352/352 - 20s - 56ms/step - accuracy: 0.5387 - loss: 1.2927 - val_accuracy: 0.4786 - val_loss: 1.4489
Epoch 17/20
352/352 - 14s - 40ms/step - accuracy: 0.5440 - loss: 1.2762 - val_accuracy: 0.4942 - val_loss: 1.4190
Epoch 18/20
352/352 - 21s - 58ms/step - accuracy: 0.5476 - loss: 1.2621 - val_accuracy: 0.5000 - val_loss: 1.4078
Epoch 19/20
352/352 - 14s - 41ms/step - accuracy: 0.5498 - loss: 1.2536 - val_accuracy: 0.5022 - val_loss: 1.4182
Epoch 20/20
352/352 - 21s - 61ms/step - accuracy: 0.5580 - loss: 1.2340 - val_accuracy: 0.5016 - val_loss: 1.3994

Results:

,Stage,Activation,Hidden Units,# Hidden Layers,Optimizer,Loss,Test Accuracy
4,Change optimizer,sigmoid,512,2,adam,sparse_categorical_crossentropy,0.5125
5,Change loss (one-hot),sigmoid,512,2,adam,categorical_crossentropy,0.5036
2,Units Sweeps (1 layer),sigmoid,512,1,rmsprop,sparse_categorical_crossentropy,0.4904
1,Units Sweeps (1 layer),sigmoid,256,1,rmsprop,sparse_categorical_crossentropy,0.4871
3,Add hidden layer,sigmoid,512,2,rmsprop,sparse_categorical_crossentropy,0.4774
0,Units Sweeps (1 layer),sigmoid,128,1,rmsprop,sparse_categorical_crossentropy,0.4511

Best tuned configuration:

,Stage,Activation,Hidden Units,# Hidden Layers,Optimizer,Loss,Test Accuracy
4,Change optimizer,sigmoid,512,2,adam,sparse_categorical_crossentropy,0.5125

We chose the ReLU activation function because it is one of the most common activation functions in neural networks. ReLu outputs zero for negative values and the input value for positive values. Helps reduce the vanishing gradient problem and allows the model to train faster and efficiently. ReLU is computationally simple and performs well in deep learning. Tanh was chosen because it outputs values beween [-1, 1], making it zero centered. Zero centered can help improve optimization compared to sigmoid because gradients may balance more effectively during training. Tanh can capture nonlinear relationships than sigmoid. Sigmoid was chosen because it outputs values between 0 and 1. It provided a useful comparison to the other activation functions.

The sigmoid activation function seemed to achieve the highest test accuracy with (0.4533) outperforming tanh (0.4148) and ReLu (0.4314). Sigmoid performed better for this specific dataset configuration. May be due to the shallow structure of the model. The neural network was not very deep, the vanishing gradient issue associated with sigmoid was not visible on this performance.

Tuning the model using sigmoid activation function and increasing the number of neurons in the hidden layers by 128, 256, and 512 increased the models capacity to learn more patterns. The larger hidden layers improved performance but began to level off as the number of neurons increased.

Adding hidden layers allowed the model to capture nonlinear relationships. The deeper model improved performance compared to the single hidden layer.

Changing the optimizer from RMSprop to Adam futher improved stability and test accuracy. Adam's adaptive learning rate lead to efficient training.

Sparse categorical crossentropy to categorical crossentropy did not really change much in the performance. Both loss functions are essentially the same.

Tuning the model improved performance over the orignal models. The best results were achieved with sigmoid activation functions with increased hidden units, layers and optimizer. Maybe things would be different with deeper networks as well as epochs.